version: "3.8"

services:
  # PostgreSQL Database
  db:
    image: postgres:17.4-alpine
    container_name: luckyluke-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: venom
      POSTGRES_PASSWORD: root#370
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend API
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: luckyluke-api
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=venom
      - DB_PASSWORD=venom#370
      - DB_NAME=luckyluke
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: luckyluke-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  postgres_data:
